[workspace]
members = [
    "mamoru-core",
    "mamoru-core-c",
    "cosmos-account-generator",
]

[workspace.dependencies]
# Use custom `cosmrs` due to breaking dependency with `sui` integration.
# See https://github.com/Mamoru-Foundation/cosmos-rust/commit/61b33b3ec70200c823a8d1ab2f38868dc67469fd
cosmrs = { git = "https://github.com/Mamoru-Foundation/cosmos-rust.git", rev = "8c971b29"}
