[package]
edition = "2021"
name = "mamoru-core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethnum = {version = "1", features = ["serde"]}
jsonpath_lib = "0.3"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
