[package]
edition = "2021"
name = "mamoru-core"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# Disabling because:
# - we don't need it yet
# - doctests fail on generated code
doctest = false

[dependencies]
async-stream = "0.3"
base64 = "0.13"
# Use custom `cosmrs` due to breaking dependency with `sui` integration.
# See https://github.com/Mamoru-Foundation/cosmos-rust/commit/61b33b3ec70200c823a8d1ab2f38868dc67469fd
cosmrs = { git = "https://github.com/Mamoru-Foundation/cosmos-rust.git", rev = "44345956", features = ["grpc", "grpc-tls"] }
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
envy = "0.4"
ethnum = { version = "1", features = ["serde"] }
futures = "0.3"
jsonpath_lib = "0.3"
prost = "0.11"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
tokio-rayon = "2.1"
tonic = { version = "0.8", features = ["tls"] }
tracing = "0.1"

[build-dependencies]
tonic-build = "0.8"

[dev-dependencies]
env_logger = "0.9.1"
reqwest = { version = "0.11", features = ["json"] }
test-log = { version = "0.2.11", features = ["trace"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }
