[package]
name = "mamoru-core-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[features]
headers = ["safer-ffi/headers"]

[dependencies]
paste = "1.0"
safer-ffi = {version = "0.0.10", features = ["log", "proc_macros"]}
mamoru-core = {path = "../mamoru-core"}
