name: CI
on: push
env:
  CARGO_TERM_COLOR: always

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt, clippy
      - name: Run linting
        run: |
          cargo fmt -- --check
          cargo clippy
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: true
      - name: Build
        run: cargo build --verbose

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: true
      - name: Run tests
        run: cargo test --verbose

  slack-notify:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs:
      - linting
      - build
      - tests
    steps:
      - uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
                "branch": "${{ github.ref_name }}",
                "linting": "${{ needs.linting.result == 'success' && '✅' || '❌' }}",
                "build": "${{ needs.build.result == 'success' && '✅' || '❌' }}",
                "tests": "${{ needs.tests.result == 'success' && '✅' || '❌' }}",
                "run_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: true
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --quiet
      - name: Generate code coverage
        run: cargo llvm-cov
